version: '3.7'

services:
  flask-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml

  tempo:
    image: grafana/tempo
    ports:
      - "4317:4317"
      - "3200:3200"
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml
    command: -config.file=/etc/tempo/tempo.yml - distributor.log_received_spans.enabled -log.level=debug
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
