name: CI/CD for Flask Server on Local Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#очень важный комментарий
jobs:
  build-and-redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t flask-app:latest .

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for service to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/ui; then
              echo "Service is ready!"
              exit 0
            fi
            sleep 1
          done
          echo "Service did not become ready after 30 attempts."
          exit 1
